apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ik7rmvwk7-go 
  janus-idp.io/tekton: ik7rmvwk7-go
  backstage.io/kubernetes-id: ik7rmvwk7-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ik7rmvwk7-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml