apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ik7rmvwk7-go
  janus-idp.io/tekton: ik7rmvwk7-go
  backstage.io/kubernetes-id: ik7rmvwk7-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ik7rmvwk7-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
